name: Review Requested

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - opened
      - synchronize
      - edited
      - converted_to_draft
      - ready_for_review

  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

  issue_comment:
    types:
      - created

jobs:
  Review:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: mobsuccess-devops/github-actions-review@master
        with:
          github-token: ${{ github.token }}
